#端口
server:
  port: 9001
#注册中心客户端配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    prefer-ip-address: true
#命名
spring:
  application:
    name: AIGOU_ZUUL
#zuul配置
zuul:
  routes:
    #第一种写法
    #aigou_plat: /employee/**
    #第二种写法
    plat.serviceId: aigou_plat
    plat.path: /employee/**

    product.serviceId: aigou_product
    product.path: /product/**
  ignored-services: "*"
  prefix: /aigou
