server:
  port: 8848
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: AIGOU_CONFIGSERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/1104317430/aigou_config.git
          username: 1104317430@qq.com
          password: zhuhai321.