eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    prefer-ip-address: true #使用ip注册到注册中心
server:
  port: 4399
  max-http-header-size: 4048576 #设置参数大小
spring:
  application:
    name: COMMON-PROVIDER